# 站点基础信息
title: 梁家浩 | 个人主页  
url: "https://LMKLJH.github.io"
baseurl: ""

# 核心：换成数学友好主题（自带 MathJax）
remote_theme: vsoch/jekyll-math@v1.0.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# 公式渲染配置（自动生效，无需额外 JS）
markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
