title: 梁家浩 | 个人主页
url: "https://LMKLJH.github.io"
baseurl: ""

# 用最稳的 minima 主题，和你 Gemfile 里的依赖一致
remote_theme: jekyll/minima@v2.5.1
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# 只保留最基础的 Markdown 解析，不加任何公式配置
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
