# 站点基础信息
title: 个人主页
url: "https://LMKLJH.github.io"
baseurl: ""

# 主题配置
theme: minima
minima:
  skin: dark
  show_excerpts: false
  navigation_items:
    - title: 主页
      url: /

# 通用配置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 精简排除项
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
